src/stylemacro.jl

This seems like it might be necessary to avoid precompile problems otherwise seen in https://github.com/JuliaLang/julia/pull/51811?
Thoughts on this would be welcome.

Within-module eval can break precompile

---

src/faces.jl

This face is used in the repl to alert a user that an action had to effect, for example when a user presses `backspace` when a user hasn't input anything, or uses `Tab` for completion and there are no completion suggestions.

add `repl_prompt_beep` face

---

src/stylemacro.jl
test/runtests.jl

Should fix windows CI.
Waiting to push the fix till CI fails with the tests.
Closes #15 which was, in comparison to this, mucking around in the dark waiting for the lights to turn green.

Add tests for newline handling and fix support for windows.

---

.github/workflows/CI.yml

StyledStrings.jl does not currently support older versions of Julia. These lines can be uncommented when that support is added.

Disable CI for older versions of Julia

---

src/stylemacro.jl

c.f. https://github.com/JuliaLang/julia/pull/51747

remove use of length of Stateful

---

src/faces.jl

This makes the priority of inheritance better match the priority and
semantics of the merge function (in general). To account for this
change, the argument order in a few face merge invocations needs to be
flipped.

Swap inheritance processing in face merge

---

src/io.jl

It is worth taking note of the fact that the "default" colour in a
terminal can be set with the -9 ANSI codes. Without this, dodgy control
codes can be emitted when the current default face is changed, resulting
in visual artifacts.

Setting the terminal colour to :default is special

---

.github/workflows/CI.yml
.gitignore
docs/Makefile
docs/Project.toml
docs/make.jl
docs/src/index.md
docs/src/internals.md
src/regioniterator.jl

The two commits build everything and fail due to failed doctests due to #8 
The remaining commits should fix that failure, fix #8, make CI green, and unblock https://github.com/JuliaLang/julia/pull/51869

Build docs in CI

---

docs/src/index.md

This should resolve the current conflict with the docstrings from Base's
documentation. 🤞

Restrict the Base docstrings included in the docs

---

src/io.jl

This method was overlooked when the `AnnotatedString(::String, ::Vector{Pair{Symbol, <:Any}})` constructor was removed.

Fix showing AnnotatedChar with colour

---

src/stylemacro.jl

Closes #28 (which see).
Will merge shortly if everything appears to be in order.

Revert reservation of ":" within styled regions

---

src/io.jl

Just the `where {F <: Function}` change should be enough to correct type
inference in theory, but `Base.return_type` still gave `Any` with just
that change, so we're also adding a type assertion to the `write` method.

Fix (return) type inference of Base.write

---

src/legacy.jl

This allows for providing an AnnotatedIOBuffer to various IO-accepting printing functions (e.g. show, showerror) and obtaining the annotations that would be formed from straightforwardly switching to StyledStrings.
Requires https://github.com/JuliaLang/julia/pull/51807
-----

printstyled specialisation for AnnotatedIOBuffer

---

src/stylemacro.jl
test/runtests.jl

The advantage here is that you don't escape it twice, so that `styled"\\"` doesn't need double the number of `\\` each time to get one more `\` at the end (the downside is that less common forms such as `@styled_str "\\"` still apply the `unescape_string` call twice and we cannot catch that)
```
julia> styled""
""
julia> styled"\\"
"\\"
julia> styled"\\\\"
"\\"
julia> styled"\\\\\\"
"\\\\"
julia> styled"\\\\\\\\"
"\\\\"
```

Call escape_raw_string to make parsing more predictable

---

src/stylemacro.jl

In the expansion, it's assumed that there is at least one charater after
an escaped character, but this is not always the case.

Fix invalid non-empty state assumptions in macro

---

docs/src/internals.md
src/legacy.jl

When a given "legacy color" argument is not in fact a recognised color
name, `legacy_color` should return nil, and indeed it does when the
argument is a string.
However, the color symbol method will just return the symbol argument if
it is not recognised, creating an inconsistency in the behaviour.
Instead, it should return nothing, as the string case does.
This change is made, and a little of the surrounding code rearranged for
clarity.

More consistent legacy color conversion

---

src/faces.jl
src/regioniterator.jl

For consistency, calling `annotations` on an AnnotatedString, whether an
index or range is specified, now always returns a vector of
region-annotation tuples.
Previously, when an index was specified, only the annotations would be
returned. Thus, code that relies on this previous behaviour must now
apply `last` to each element of the returned vector.

Adjust to changed annotations function return form

---

src/io.jl
test/runtests.jl

In https://github.com/JuliaLang/julia/commit/f117a500ca93, the AnnotatedIOBuffer type was introduced. If you write from an AnnotatedIOBuffer to another kind of IO, currently all styling information is lost.
This seems undesirable, and we can make it work more like writing an AnnotatedString to IO ... by converting this to an AnnotatedString write within a specialised write method.
The conversion surely adds overhead, but it's a very staightforward way to make this work. If this ends up being a legitimate performance concern, we can always revisit this and either:
- Add a specialised code path for AnnotatedIOBuffer
- Try to make the current AnnotatedString-oriented methods more
generic (somehow)
The utility of this was first expressed in …

Introduce specialised write for AnnotatedIOBuffer

---

src/styledmarkup.jl

Once again, I'd just be pushing these commits I could, without this pointless
indirection, but I can't.

Annotation tweaks in preparation for Base changes

---

src/StyledStrings.jl

In rare cases, it is possible that the DEPOT_PATH could be empty. As
such, the assumption that first(DEPOT_PATH) will produce a valid value
needs to be removed, in which case we simply won't automatically load a
user faces.toml.

Load no faces.toml when the DEPOT_PATH is empty

---

README.md
docs/src/examples.md
docs/src/index.md

- Better hint at the package capabilities in readme
- Mention the importance of semantic names in docs

Docs tweaks

---

docs/src/internals.md
src/styledmarkup.jl

The previous code pattern using `takewhile` relied on Julia's type inference to produce correct results. In particular, it relied on `takewhile(f, x) |> collect` to correctly infer to `Vector{<:Tuple{Char, Any}}`. However, type inference in Julia is an optimization, and should not be relied on to produce the correct answer.
Instead, use a normal function to replace the functional style of programming.
Edit: I haven't been able to run tests locally, so this might not work as-is. See #63

Use a function over a closure to handle poor inference

---

src/regioniterator.jl

Currently the correctness of this depends on the exact typejoin logic for comprehensions. That's probably reasonably safe, but it can break when developing Base, and since this is a stdlib, let's be a good citizen and annotate the types.

Add types to some comprehensions

---

src/io.jl

As raised in https://github.com/JuliaLang/julia/issues/55198, once we look at `AbstractString` types outside of Core/Base, their `print` methods can be meaningfully different to `write` + returning `nothing`.
As such, instead of delegating printing to `write`, we need to call `_ansi_writer` asking it to use the `print` function.

Treat printing as more than a nothing-return write

---

src/io.jl

A few terminals (Kitty) only set the `Su` cap not `Smulx`, we should recognise either as sufficient for fancy underlines.

Check for underline term capability flag

---

src/styledmarkup.jl

It's recently come to my attention that `RefValue` is actually what `Ref` looks like at a glance.

Use concrete refs in macro parser state struct

---

docs/src/internals.md
src/regioniterator.jl
test/runtests.jl

Since we removed the ordering restriction on annotations to improve the semantics of annotation modification, each `annotations(str)` call became `O(n)` which is fine for a once off, but use it in a loop as `eachregion` does and now it's `O(n m)`. That's pretty underwhelming.
We can improve this to `O(n log n)` by pre-sorting the list of annotations, and working with it instead. A bit more complexity is needed to do this while preserving the semantics, but it can be worth it for long strings. With a 100,000 char string with 20,000 annotations, print time goes from ~0.4s to 0.015s on my machine.
-----
This improvement has been prompted by #72.

Refactor eachregion to be O(n log n) not O(n^2)

---

src/StyledStrings.jl
src/faces.jl
src/io.jl

This avoids accidentally extending methods and makes it more clear what methods are doing overloads

do not `import` methods that are not extended and use explicit module prefix for methods that are imported

---

src/io.jl

Actually overload Base's escape_string

---

src/faces.jl

creating a new Julia array that gets reinterpreted etc can be avoided by just picking out the bytes we want

simplify code for creating a `SimpleColor` from a `UInt32`

---

src/faces.jl

How I wish I could force-push my mistakes away 😅.

Quick fix for 4d04102adf0d (Optimised SimpleColor)

---

src/faces.jl

The `get(f::Function, collection, key)` method is typically better than `get(collection, key, f())` when `f` is not trivial. This avoids calling it unless it is actually needed.
Made on top of https://github.com/JuliaLang/StyledStrings.jl/pull/75 to avoid a merge conflict.
Before (same benchmark as in #75):
```
9.508 ms (290571 allocations: 18.78 MiB)
```
After
```
8.243 ms (201949 allocations: 16.58 MiB)
```

avoid creating a new `Face` in `get` calls when `FACES` has that face available

---

src/faces.jl

Made on top of #77 to avoid some merge conflicts and have up to date benchmarks.
I was looking at why the following benchmark allocates:
```julia-repl
julia> using StyledStrings
julia> styles = Pair{Symbol, Any}[:face => :green]
1-element Vector{Pair{Symbol, Any}}:
:face => :green
julia> face = StyledStrings.getface(styles);
julia> using BenchmarkTools
julia> @btime merge($face, $face)
19.266 ns (2 allocations: 32 bytes)
```
With the following PR we instead get
```
julia> @btime merge($face, $face)
13.388 ns (0 allocations: 0 bytes)
```
The benchmark in #75 
goes from
```
8.654 ms (202611 allocations: 16.62 MiB)
```
to
```
7.972 ms (148360 allocations: 15.72 MiB)
```
Not a huge speedup but quite a big reduction in allocations which might be useful as other things improve.
I am not 100% …

use ternery instead of `ifelse` since ifelse force evaluation of the RHS

---

src/StyledStrings.jl

Loading `@with` from Base is accessing internals because `@with` is not a public symbol in Base.
See also: https://github.com/JuliaLang/julia/pull/55095#issuecomment-2226254429

Load ScopedValues symbols from their source

---

docs/src/internals.md
src/StyledStrings.jl

This is primarily motivated by reducing the amount of work that trimming is unable to remove.
It will require applications (by which I mean the actual thing that uses `StyledStrings`, for example the REPL) to call `load_customisations!` itself. If there's a good spot to add that so it automatically gets done "at the right time, when appropriate to do so" that would be even better, but I'm not sure there's an obvious spot that can be done without the potential for headaches (e.g. what if it comes up within a `withfaces` call).
For now at least, perhaps this is a reasonable compromise.

Load user-customisations lazily

---

src/styledmarkup.jl

Better for performance, avoids using internals and avoids awkward `[]`.

use const field instead of internal `RefValue`

---

src/regioniterator.jl

Ooops, I have a strong suspicion this came from some copy-paste with the RPEL, but we want Int not Int64.

Replace accidental Int64s with Ints

---

src/faces.jl
test/runtests.jl

Since we implement a custom equality function, it seems nice to have it so that `Face` objects that are equal `hash` equally too.
I'm not aware of anybody using this, but it seems nice to have. and it's just a 2-liner.

Consistent Face hashes

---

src/regioniterator.jl
test/runtests.jl

Fixes #85.
Feel free to refactor this as you see fit, but the basic idea using `thisind` seems to do the trick!

Construct substring end index using `thisind`

---

src/styledmarkup.jl
test/runtests.jl

Does what it says on the tin: improves type stability a bit, and optimises the single-interpolation case.

Slightly optimise `styled""` macro

---

docs/src/index.md

Four spaces are needed in admonitions, not two.
Amends 8332e457e11fc3feb81ff9d8a1eaf6a500e57124.

Fix markdown syntax in "Mark API as experimental"

---

src/StyledStrings.jl
src/faces.jl
src/io.jl
src/precompile.jl

This is a follow-up to #79, see the commit message for more details.

Call load_customisations! automatically, lazily

---

docs/src/examples.md
docs/src/index.md
src/StyledStrings.jl
src/io.jl
src/legacy.jl
src/regioniterator.jl
test/runtests.jl

This opens the door to shuffling parts currently implemented in Base into this stdlib without breaking any public APIs.
To try to help avoid people using `Base.Annot...` anyway, I've exported these bindings. I think this is reasonable given unlike in `Base` this library needs to be deliberately imported.

Adopt Base's annotated types/functions as API

---

docs/src/index.md
src/faces.jl
src/io.jl
src/regioniterator.jl
src/styledmarkup.jl
test/runtests.jl

By popular demand, the type of an annotation is changing from a `Tuple{UnitRange{Int}, Pair{Symbol, Any}}` to a `NamedTuple{(:region, :label, :value), Tuple{UnitRange{Int}, Symbol, Any}}`.
This necessitates some adjustments in the StyledStrings codebase.

Adjust to change of annotations type in Base

---

src/faces.jl

This removes a ton of implicit converts from this code, which are easily invalidated.

Add typeasserts to `convert(::Type{Face}, ::Dict)`

---

src/styledmarkup.jl

It is possible to have types with annotations that should be preserved other than `AnnotatedString` (such as `SubString{AnnotatedString}`), and so we should consult with `Base._isannotated` instead of just checking if the type is an `AnnotatedString` specifically.

Fix interpolation edge case dropping annotations

---

src/styledmarkup.jl

Fixes #104, hopefully doesn't introduce any new issues (no red flags from the fuzz test at least).
See the commit message for more details.

Less conservative char escaping

---

src/faces.jl
src/legacy.jl

While broadcasting is convenient syntax, it's tough on the compiler, and so likely not worth it in library code like this.

Remove instances of broadcasting

---

src/io.jl

This is the counterpart to JuliaLang/Julia@0f51a6375f2c.

Update escape_string to match the 1.12 signature

---

src/io.jl

Remove invalidating methods, and use the write-barrier introduced by Base.
This is an minimal alternative to #100.

[Speculative] Implement AnnotatedDisplay for ANSI rendering

---

src/io.jl

Write the buffer instead of using take! seems like a "why not?" to me.

Write ANSI decorated strings directly from buffer

---

src/styledmarkup.jl
test/runtests.jl

Instead of applying active styles strictly after pending styles, which is in danger of overriding more specific pending regions, convert active regions into appropriate pending regions before specificity-sorting.
Fixes #111

Adjust parsing of incomplete active styles
